### ISSUE TITLE
Crash on Android 4.x

### ISSUE THREAD

**Issue by gabrielrvd** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#10]
Hi, if use this approach in Android 4.x will crash, to solve:

Change the two lines:
fab.BackgroundTintList = ColorStateList.ValueOf(this.Element.ButtonColor.ToAndroid());

To: 
Android.Support.V4.View.ViewCompat.SetBackgroundTintList(fab, ColorStateList.ValueOf(this.Element.ButtonColor.ToAndroid()));

**Comment by SuavePirate** [comment]
A fix for this will be in the next release. I just haven't had time to update the package to netstandard 2.0 since .nuprojs are breaking with 2.0

**Comment by maxkoshevoi** [comment]
Hi, don't want to bother, but are there any updates on this?
It seems like there wasn't any releases after "2018.1.5" one.
