### ISSUE TITLE
FAB on iOS has fixed size

### ISSUE THREAD

**Issue by jgasiorowski** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#11]
When manipulating Height/WidthRequest properties of `controls:FloatingActionButton` Android version scales correctly but iOS keeps always the same size
https://github.com/SuavePirate/Xamarin.Forms.Controls.FloatingActionButton/blob/384d93e7a838dba605cbdb4e7a799f82eb559e58/src/SuaveControls.FloatingActionButton.iOS/Renderers/FloatingActionButtonRenderer.cs#L35

**Comment by SuavePirate** [comment]
A fix for this will be in the next release. I just haven't had time to update the package to netstandard 2.0 since .nuprojs are breaking with 2.0
