### ISSUE TITLE
Can not install on PCL profile259

### ISSUE THREAD

**Issue by shalinasanga** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#12]
Can not install latest on PCL profile 259

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SuaveControls.FloatingActionButton 2018.1.5'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

>

**Comment by SuavePirate** [comment]
We don't support Profile259. If you want to use this control, your PCL must be 111 or lower

**Comment by SuavePirate** [comment]
Yeah, you should switch to 111 unless you are supporting windows phone 8 silverlight
