### ISSUE TITLE
Turn the button into a menu composed of FAB

### ISSUE THREAD

**Issue by antferr** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#15]
Something similar
![menu_right_opened](https://user-images.githubusercontent.com/1942613/37024887-741cb908-212a-11e8-8094-bff5b115134d.png)

**Comment by SuavePirate** [comment]
This is outside the scope of the FAB. Just like the Android FAB, we aren't supporting the advanced animations and composition features. If you want to implement something like this, you should do it yourself with multiple FABs and animations. Just want to emphasize that this control will not be built into something greater than the Android FAB control is.
