### ISSUE TITLE
FAB Button square in shape

### ISSUE THREAD

**Issue by shreyans-wakekar** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#2]
FAB Button square in shape.

**Comment by SuavePirate** [comment]
On what platform? This isn't happening on Android and iOS.

**Comment by tonholis** [comment]
Yep. This is happening on my Android device (v6.0.1)

**Comment by CarlosMobileAppDeveloper** [comment]
@tonholis - Ensure the renderer has installed properly through NuGet. In the references folder of the Android project, you should see the two references:
- SuaveControls.FloatingActionButton
- SuaveControls.FloatingActionButton.Droid
