### ISSUE TITLE
FAB is not a circle but a rectangle

### ISSUE THREAD

**Issue by NiWe90** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#20]
Hi,
i want to use your project for implementig FAB into my Xamarin project. I downloaded the nuget package and just implemented the example on an empty page. But my Button is a rectangle and did not have the color i set to it. Would be greate if one can help me. I added the code and a screenshot:

The XAML File:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:b="clr-namespace:Xam.Behaviors;assembly=Xam.Behaviors"
             xmlns:libEx="clr-namespace:Lib.MarkupExtensions;assembly=Lib"
             xmlns:fab="clr-namespace:SuaveControls.Views;assembly=SuaveControls.FloatingActionButton"
             Title="{libEx:Translate ListShops}">
    <StackLayout Margin="32">
        <fab:FloatingActionButton x:Name="FAB" HorizontalOptions="FillAndExpand" WidthRequest="50" HeightRequest="50"  VerticalOptions="FillAndExpand" Image="ic_add_white.png" ButtonColor="#03A9F4" Clicked="Button_Clicked"/>
    </StackLayout>
</ContentPage>`

Screenshot
![screenshot_20180405-183338](https://user-images.githubusercontent.com/18171872/38379440-fefe1e2a-3900-11e8-9385-4d1d75ebb765.png)

Thank you in advance.

**Comment by SuavePirate** [comment]
Looks like you didn't call `FloatingActionButtonRenderer.InitRenderer();` in your `MainActivity`

**Comment by NiWe90** [comment]
I can not call this in my MainActivity. I added the SuaveControls.FloatingActionButton nuget package in my Forms and Android project. But VS only knows FloatingActionButton. Did i miss some reference?

**Comment by SuavePirate** [comment]
depends on which version of the package you installed. If you can't with the version you installed, then call this: 
```
var renderer = new FloatingActionButtonRenderer();
```
The issue is the renderer being linked out, so you need to reference it somewhere.
