### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with the design library

### ISSUE THREAD

**Issue by NPadrutt** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#21]
When I have a Floating Action Button added to a page i get this exception with Xamarin.Forms 2.5.1.527436
```
Java.Lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
```

It seems this is due to an obsolet constructor in the renderer.

**Comment by SuavePirate** [comment]
This has been asked and answered already: https://github.com/SuavePirate/Xamarin.Forms.Controls.FloatingActionButton/issues/6

It's the consequence of the actual Android library

**Comment by NPadrutt** [comment]
I'm sorry, but it hasn't, since there my Activity has a Style that does descend from an AppCompat Theme. 
As saied above, the solution for me was to adjust the renderer to not use the constructor who is obsolet since Xamarin.Forms 2.5.x.

**Comment by SuavePirate** [comment]
Can you send a repro? I am currently using this in xf 2.5.1 without any issues
