### ISSUE TITLE
Absolute Layout example

### ISSUE THREAD

**Issue by jon-peel** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#24]
I have been trying to get this to show properly using an absolute layout (so I can have the FAB on the bottom right, about 16 from the edge, over any other content on the screen).

I am not coming right.
I have been checking other examples of AbsoluteLayout, but nothing is working.

Could anyone create an example of this FAB in the bottom right of the layout?

**Comment by SuavePirate** [comment]
To get it in the bottom right, I wrap everything in a Grid then using `HorizontalOptions` and `VerticalOptions` with `Margin` - so something like this:

``` xml
<ContentPage>
    <Grid>
        <ListView .../>
        <fab:FloatingActionButton HorizontalOptions="End" VerticalOptions="End" Margin="0,0,16,16" ... />
    </Grid>
</ContentPage>
```

**Comment by jon-peel** [comment]
Thank you so much, that works 100%
