### ISSUE TITLE
Project can't be opened in VS 15.8.1 - "SuaveControls.FloatingActionButton.NuGet.nuproj" 

### ISSUE THREAD

**Issue by npagare** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#27]
Hi @SuavePirate,

I cloned your repo to take a look at the sample app.

Apparently, while opening it in VS 15.8.1 I am getting following error  -
**May be this project need to be ported to a newer project template under 15.8 ?** 

![image](https://user-images.githubusercontent.com/26844611/44806160-d066c500-ab8b-11e8-949b-eb1b99cf82b1.png)

Thanks,

**Comment by SuavePirate** [comment]
You have to install the nuproj extension. That project is only used to build the nuget package.
