### ISSUE TITLE
[Request] Example List view

### ISSUE THREAD

**Issue by welcometoall** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#3]
Can you add a example to put a Floating Action Button on top of List view and also support for UWP platform.

**Comment by tonholis** [comment]
This is what I did:

```
<Grid>
    <ListView />
    <suave:FloatingActionButton HorizontalOptions="End" VerticalOptions="End" Margin="0,0,10,10" />
<Grid>
```

**Comment by SuavePirate** [comment]
Yeah this is basically what the layout should look like. If you want to add some other behaviors such as attaching to a `ListView` so it can hide on scroll, then I would suggest creating a feature request in the Issues here and in the short-term add an event listener for the ListView and animate the FAB away depending on the scroll direction.

**Comment by welcometoall** [comment]
@tonholis This works!
