### ISSUE TITLE
Press event not working?

### ISSUE THREAD

**Issue by kineese** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#30]
Hello!
First off - thanks for this extension! There is a minor issue when adding the NuGet Package:

> Warning	NU1701	Package 'SuaveControls.FloatingActionButton 2018.1.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Don't know if the issue here is on my side or on yours.

Main Issue here:
I want to show a ActionSheet when pressing the FAB but for some reason the event is never invoked.

Here is my sample code
XAML

            <fab:FloatingActionButton HorizontalOptions="EndAndExpand" VerticalOptions="EndAndExpand"
                                      HeightRequest="90"
                                      WidthRequest="80"
                                      Clicked="AddNewScan"
                                      Pressed="Test">
                <fab:FloatingActionButton.Image>
                    <OnPlatform x:TypeArguments="FileImageSource">
                        <On Platform="Android" Value="ic_add_a_photo_white_48dp.png" />
                        <On Platform="iOS" Value="ic_add_a_photo_white_48pt.png" />
                    </OnPlatform>
                </fab:FloatingActionButton.Image>
            </fab:FloatingActionButton>

Code-Behind:
       
     private void Test(object sender, EventArgs e)
        {
            Console.WriteLine($"?!?!?!?!BUTTON PRESS WORKS?!?!?!?!");
        }

Hope you could help me out!
Thanks
Kineese

**Comment by SuavePirate** [comment]
I haven't updated this package to support .netstandard since I haven't really had the time which is why it was restored with .net framework.

As for your click event, right off the bat it seems like your `Clicked` event handler method name is different from your code behind method name.

see:
`Clicked="AddNewScan"`

`private void Test(...)`

**Comment by kineese** [comment]
> I haven't updated this package to support .netstandard since I haven't really had the time which is why it was restored with .net framework.
> 
> As for your click event, right off the bat it seems like your `Clicked` event handler method name is different from your code behind method name.
> 
> see:
> `Clicked="AddNewScan"`
> 
> `private void Test(...)`

Thanks for the fast reply!
My bad.. I just pasted only a small part of my sample code. The Click-Event is working perfectly!
It's more about the _Pressed_ event which isnt't working. To be more precise here the modified sample-code
```
     <fab:FloatingActionButton HorizontalOptions="EndAndExpand" VerticalOptions="EndAndExpand"
                                  HeightRequest="90"
                                  WidthRequest="80"
                                  Pressed="Test"/>
```

Code-behind:
```
private void Test(object sender, EventArgs e)
    {
        Console.WriteLine($"?!?!?!?!BUTTON PRESS WORKS?!?!?!?!");
    }
```

Thanks in advance!
Kineese

**Comment by SuavePirate** [comment]
Oh gotcha. This is built ontop of the `Xamarin.Forms.Button` and when it was originally made, the `Pressed` event didn't exist so it isn't supported here. You should use the `Command` or `Click` event

**Comment by kineese** [comment]
Okay I guess I got the total wrong idea behind the meaning of Press-Event. I thought it's a long-press event which invokes when the user clicks and holds the button.
My bad! Anyways thanks again
