### ISSUE TITLE
Navigation through DelegateCommand from Prism Library never gets called

### ISSUE THREAD

**Issue by joeizang** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#4]
Hello there,

I have this small issue where when I setup the FAB and set up the command to navigate like so:

This is ContentPage with FAB in it:
    `    <?xml version="1.0" encoding="utf-8" ?>
        <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             xmlns:control="clr-namespace:CashFlowBuddie.CustomRenderers;assembly=CashFlowBuddie"
             x:Class="CashFlowBuddie.Views.IncomeSummaryPage"             
             Title="CashFlow Summary">
    <StackLayout Margin="32">
        <control:FloatingActionButton x:Name="FAB" WidthRequest="50" HeightRequest="50" 
        HorizontalOptions="EndAndExpand" VerticalOptions="EndAndExpand" Image="ic_add_black" 
        ButtonColor="#ffa4a2" Command="{Binding AddIncomeCommand}"/>
        </StackLayout>
        </ContentPage>`

This is my page viewmodel with the DelegateCommand setup:

    public class IncomeSummaryPageViewModel : ViewModelBase
    {
        private readonly INavigationService _navigationService;
        private readonly IPageDialogService _dialogService;
        public DelegateCommand AddIncomeCommand { get; set; }
        public IncomeSummaryPageViewModel(INavigationService navigationService, IPageDialogService 
            dialogService) : base(navigationService, dialogService)
        {
            Title = "Income Summary";
            AddIncomeCommand = new DelegateCommand(AddIncome);
            _navigationService = navigationService;
            _dialogService = dialogService;
        }
        private void AddIncome()
        {
            //dialogService.DisplayAlertAsync("Hey", "FAB click is handled by command", "Yipee!", "Dang It!");
            _navigationService.NavigateAsync(
            "/NavigationPage/MainDetailPage/IncomeSummaryPage/AddIncomePage", null,true,true);
        }
    }

It doesn't work! If I am not navigating anywhere using the dialogService, I get a dialog with the message I commented out in the code above. I am not sure what to do here so I thought maybe you could help?

**Comment by SuavePirate** [comment]
If you replace the FAB with a regular button to test, are you able to navigate? I want to make sure this is definitely an issue with the control's command propagation before chasing it down the rabbit hole.

**Comment by joeizang** [comment]
Hello sir,

I tried that and I wasn't able to. But I tried navigating using the clicked event and putting code in the code behind :-( and it worked. So not really sure what is going on. I was going through the feature requests and I am also in support of a fully featured example of the FAB with listviews and all.

God bless you for all the work you have done on the FAB.

**Comment by SuavePirate** [comment]
So just to clarify, using a regular button does not work either? If that's the case, I'm going to close out this issue since it doesn't seem to be a problem with the FAB itself. And as always, I appreciate the support 😄

**Comment by joeizang** [comment]
Yeah that is the fact right now. I have had to use the code behind and things are ok. Thanks again.
