### ISSUE TITLE
Button color not  set

### ISSUE THREAD

**Issue by nuwankarunapala** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#5]
Hi,
Really exiting to see FAB in xamarin forms. Grate work.

i have  got small issue when I am trying this out , button not getting color although i have assign it
can please help me on this , 

my code 
<Grid>
      
            <ListView x:Name="list" 
                  ItemTapped="list_ItemTapped" 
                  HasUnevenRows="True" 
                  BackgroundColor="LightGray" 
                  IsPullToRefreshEnabled="True"
              SelectedItem="{Binding SelectedQuote, Mode=TwoWay}"
              CachingStrategy="RecycleElement"
                  RefreshCommand="{Binding RefreshCommand}"
                  IsRefreshing="{Binding IsRefreshing}">
            
        <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Frame   HasShadow="True"   CornerRadius="7"    Padding="5">
                        <Grid RowSpacing="0">
                            <Grid.RowDefinitions >
                                <RowDefinition Height="auto" />
                                <RowDefinition Height="1.5*" />
                                <RowDefinition Height="40" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>

                            <Label Text="{Binding item}" BackgroundColor="{Binding itemColor}" TextColor="White" FontAttributes="Bold" ></Label>
                            <Label Text="{Binding description}" BackgroundColor="White" Grid.Row="1" ></Label>
                            <StackLayout Grid.Row="2" Orientation="Horizontal" Padding="0,5,0,5" HorizontalOptions="FillAndExpand">
                                <controls:CircleImage x:Name="imageview"  Source="{Binding Image}" Aspect="AspectFill" HorizontalOptions="Start"></controls:CircleImage>
                                <controls:CircleImage x:Name="imageview2"  Source="star.png" IsVisible="{Binding isFavarit}" Aspect="AspectFill" HorizontalOptions="EndAndExpand"></controls:CircleImage>
                            </StackLayout>
                        </Grid>
                        </Frame>
                </ViewCell>
                    </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>

        <fbcontrols:FloatingActionButton HorizontalOptions="End" VerticalOptions="End" Margin="0,0,10,10" WidthRequest="50" HeightRequest="50" Image="ic_add_white.png"  ButtonColor="Blue" />
    </Grid>

![screenshot_2017-10-21-00-55-37](https://user-images.githubusercontent.com/5153787/31838497-b5170c74-b5fa-11e7-8e68-5816dec2ddd1.png)

**Comment by SuavePirate** [comment]
Seems like an issue with the renderer not loading or being linked out. We are looking into this now.

**Comment by nuwankarunapala** [comment]
Thank you  very much for your quick reply .

**Comment by nuwankarunapala** [comment]
Hi Any Update on this issue?

**Comment by SuavePirate** [comment]
Yeah, it's on my stack of things I'm working on in the next couple weeks. If you need a short term solution, instantiate a new `FloatingActionButtonRenderer` in your `MainActivity` to ensure that the renderer doesn't get linked out.

**Comment by nuwankarunapala** [comment]
Thank you , I will try that .

**Comment by jemmett92** [comment]
Did that work? I can't seem to instantiate a new FloatingActionButtonRenderer, what exactly do you type?

**Comment by webmasterdevlin** [comment]
Works on me. Xamarin Forms and Andriod Support Libraries in my projects are even up to date. Thanks, Alex.

**Comment by CarlosMobileAppDeveloper** [comment]
@nuwankarunapala  - Ensure the renderer has installed properly through NuGet. In the references folder of the Android project, you should see the two references:
- SuaveControls.FloatingActionButton
- SuaveControls.FloatingActionButton.Droid

**Comment by SuavePirate** [comment]
I've updated the nuget package to include an empty `Initialize` method on the android renderer which can be called within your `MainActivity` to ensure that the reference to the renderer does not get linked out for those of you who are having issues with it.
