### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with the design library.

### ISSUE THREAD

**Issue by TimBarton** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#6]
Hi,

I am getting this error.  I added the l;ibrary to Protable, IOS, and Droid.  I also initiated the FloatingActionButtonRenderer.

Thanks

**Comment by SuavePirate** [comment]
This means your activity's style needs to inherit from App compat. You can set this in the Activity Attribute above your Activity or in your Android Manifest file.

**Comment by SuavePirate** [comment]
Closing since this is simply an Android requirement to use the FAB in general. Read more about it here: https://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity
