### ISSUE TITLE
Android has square shadow - not circle

### ISSUE THREAD

**Issue by CarlosMobileAppDeveloper** [SuavePirate/Xamarin.Forms.Controls.FloatingActionButton#7]
The button shadow around the floating action button in Android is a square, not a circle.
Currently using:
 - Android 8.0 as target
 - Xamarin.Android.Support.Compat v26.1.0.1
 - Xamarin.Forms v2.5.0.91635

**Comment by tonholis** [comment]
Yes, it seems that parent's view is clipping the button's shadow.

https://stackoverflow.com/questions/31507097/floating-action-buttons-shadow-clipping-at-view-margins

**Comment by tonholis** [comment]
I tested setting **fab.UseCompatPadding = true** in the renderer.
![image](https://user-images.githubusercontent.com/5032355/33175687-cce3406c-d05c-11e7-931a-1d2f4820daee.png)


![image](https://user-images.githubusercontent.com/5032355/33175779-19ff58cc-d05d-11e7-8c77-85d7746117c0.png)


I got the solution from here: https://stackoverflow.com/a/36822975

**Comment by SuavePirate** [comment]
Good call, I was thinking that might be it. If you want to create a Pull Request with a fix, I would appreciate the help! If not, I'll get to it when I'm back in town.

**Comment by marcelinhovt** [comment]
I downloaded the nuget today and i have this problem. Do I have to insert this renderer ?

**Comment by SuavePirate** [comment]
Do you have a screenshot? Could be the parent layout cutting it off.

**Comment by mcferdev** [comment]
I don´t think so. I was using the version 2017.10.17 and was Ok. So, I
upgraded to the 2018.1.15 and got this. I wrote the renderer but the
problem also persists...
So, i downgraded to the 2017.10.17 and using it.

2018-03-01 17:20 GMT-03:00 Alex Dunn <notifications@github.com>:

**Comment by mcferdev** [comment]
Any Progress ?
